version: 2.1

jobs:
  build-docker-image: 
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image with authenticated pull and push to Quay
          command: | 
            echo "$DOCKERHUB_PASSWORD" | docker login -u=$DOCKERHUB_USERNAME --password-stdin
            docker build -t quay.io/aofarrel/rchecker:circleci-push ./docker
            echo "$QUAY_PASSWORD" | docker login -u=$QUAY_USERNAME --password-stdin quay.io
            docker push quay.io/aofarrel/rchecker
workflows: 
  main:
    jobs:
      - build-docker-image:
          context: test-secret